service: serverless-project
custom:
  secrets: ${file(secrets.json)}

useDotenv: true
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '2'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.secrets.NODE_ENV}

  environment: 
    DB_NAME: ${self:custom.secrets.DB_NAME}
    DB_USER: ${self:custom.secrets.DB_USER}
    DB_PASS: ${self:custom.secrets.DB_PASS}
    DB_HOST: ${self:custom.secrets.DB_HOST}
    DB_PORT: ${self:custom.secrets.DB_PORT}
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
  lambdaHashingVersion: 20201221

functions:
  customers:
    handler : handlers/getcustomer.handler
    events:
      - http:
          method: get
          path: customer
  customersid:
    handler : handlers/getcustomerbyid.handler
    events:
      - http:
          method: get
          path: customer/{id}
  insertcustomers:
    handler : handlers/createcustomer.handler
    events:
      - http:
          method: post
          path: customer
  updatecustomers:
    handler : handlers/updatecustomer.handler
    events:
      - http:
          method: put
          path: customer/{id}
  deletecustomers:
    handler : handlers/deletecustomer.handler
    events:
      - http:
          method: delete
          path: customer/{id}
  checkconnectionseq:
    handler : handlers/checkconnection.checkconnection
    events:
      - http:
          method: get
          path: /
  getcustomersseq:
    handler : handlers/getcustomerseq.handler
    events:
      - http:
          method: get
          path: customerseq
  getcustomerIdseq:
    handler : handlers/getcustomeridseq.handler
    events:
      - http:
          method: get
          path: customerseq/{id}
  createcustomerseq:
    handler : handlers/createcustomerseq.handler
    events:
      - http:
          method: post
          path: customerseq
  updatecustomerseq:
    handler : handlers/updatecustomerseq.handler
    events:
      - http:
          method: put
          path: customerseq/{id}
  deletecustomerseq:
    handler : handlers/deletecustomerseq.handler
    events:
      - http:
          method: delete
          path: customerseq/{id}
  getcustomervand:
    handler : handlers/getcustomervand.handler
    events:
      - http:
          method: get
          path: customervand
  getcustomeridvand:
    handler : handlers/getcustomerbyidvand.handler
    events:
      - http:
          method: get
          path: customervand/{id}
  createcustomervand:
    handler : handlers/createcustomervand.handler
    events:
      - http:
          method: post
          path: customervand
 

  



